# metadata
run_name: 'Sochi'
logging: 'True'
# characteristic number for map
perf_num: 6

# map paths
#map_path: './Sochi_obstacles'
map_path: './Sochi_map'
map_ext: '.png'

# Start\ Finish Line: -0.0440806; -0.8491629; 3.4034118;
# T1 ():

sx: 0.8007017
sy: -0.2753365
stheta: 4.1421595


sx2: 0.8162458
sy2: 1.1614572
stheta2: 4.1446321



# raceline path and indices
wpt_path: './Sochi_raceline.csv'
wpt_path2: './Sochi_centerline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345